name: Android CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build all flavor variants
        run: |
          ./gradlew assembleWhatsappDebug assembleBusinessDebug -Pminify=true

      - name: Get short SHA
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Upload WhatsApp flavor artifacts
        uses: actions/upload-artifact@v4
        with:
          name: whatsapp-debug-app-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/whatsapp/debug/app-whatsapp-debug.apk

      - name: Upload Business flavor artifacts
        uses: actions/upload-artifact@v4
        with:
          name: business-debug-app-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/business/debug/app-business-debug.apk

      - name: Upload to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: WaEnhancer ${{ env.SHORT_SHA }}
          body_path: changelog.txt
          files: |
            app/build/outputs/apk/whatsapp/debug/app-whatsapp-debug.apk
            app/build/outputs/apk/business/debug/app-business-debug.apk
          tag_name: debug-${{ env.SHORT_SHA }}
